"""Generate narrative sections (README results block, paper Results/Discussion/
Conclusion, research summary) from the produced artefacts.

Every number written here is read from results/tables/*.csv or
results/processed/*.parquet; nothing is typed by hand. Re-run after any change
to the backtest so the prose can never drift from the numbers.
"""
import glob
import json
import os
import re

import numpy as np
import pandas as pd

ROOT = "/opt/data/kvab"
TAB = f"{ROOT}/results/tables"
PROC = f"{ROOT}/results/processed"

LABEL = {"kronos": "Kronos (zero-shot)", "azb_s42": "AlphaZeroBeta",
         "azb_s123": "AlphaZeroBeta (s123)", "azb_s456": "AlphaZeroBeta (s456)",
         "momentum": "Momentum (12-1)", "ridge": "Ridge (walk-forward)",
         "index_ref": "S\\&P 500 buy-and-hold", "equal": "Equal weight",
         "maxsharpe": "Max-Sharpe", "mincorr": "Min-correlation"}


def f(x, nd=3):
    try:
        x = float(x)
    except Exception:
        return "--"
    return "--" if not np.isfinite(x) else f"{x:.{nd}f}"


def load(name):
    p = f"{TAB}/{name}.csv"
    return pd.read_csv(p) if os.path.exists(p) else None


def md_table(header, rows):
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def verdict(port, sig, rep):
    """The statistical honesty check, computed rather than asserted."""
    v = {}
    if port is not None:
        d = port.set_index("model")
        v["n_arms"] = len(d)
        v["best"] = d["sharpe"].idxmax()
        v["best_sharpe"] = float(d["sharpe"].max())
        for m in ["kronos", "azb_s42", "momentum", "ridge"]:
            if m in d.index:
                v[f"sharpe_{m}"] = float(d.loc[m, "sharpe"])
                v[f"corr_{m}"] = float(d.loc[m, "corr"])
                v[f"mdd_{m}"] = float(d.loc[m, "max_dd"])
    if sig is not None:
        for _, r in sig.iterrows():
            key = f"{r['model_a']}_vs_{r['model_b']}"
            v[key] = {"diff": float(r["diff"]), "ci": (float(r["ci_lo"]), float(r["ci_hi"])),
                      "p": float(r["p_value"]), "significant": bool(r["ci_lo"] > 0 or r["ci_hi"] < 0)}
    if rep is not None:
        v["repro"] = rep.to_dict("records")
    return v


def main():
    port = load("T6_portfolio_main")
    sig = load("T7_significance")
    rep = load("T4_reproduction")
    fore = load("T5_forecasting")
    reg = load("T8_regimes")
    cost = load("T9_cost_sensitivity")
    seeds = load("T11_seeds")
    comp = load("T10_computational")
    dm = None
    p = f"{TAB}/T5_diebold_mariano.json"
    if os.path.exists(p):
        dm = json.load(open(p))
    v = verdict(port, sig, rep)
    json.dump(v, open(f"{TAB}/verdict.json", "w"), indent=1, default=str)

    # ---------------------------------------------------------- README block
    blocks = []
    if port is not None:
        rows = []
        for _, r in port.iterrows():
            rows.append([LABEL.get(r["model"], r["model"]), f(r["cagr"]), f(r["ann_vol"]),
                         f(r["sharpe"]), f(r["sortino"]), f(r["max_dd"]), f(r["beta"]),
                         f(r.get("turnover_ann"), 1)])
        blocks.append("### Portfolio results, baseline costs (generated)\n\n" +
                      md_table(["Model", "CAGR", "Vol", "Sharpe", "Sortino", "Max DD",
                                "Beta", "Turnover"], rows))
    if rep is not None:
        rows = [[r["metric"], r["published"], r["reproduced"], r["pct_diff"]]
                for _, r in rep.iterrows()]
        blocks.append("### Published vs reproduced, S&P 500 (generated)\n\n" +
                      md_table(["Metric", "Published", "Reproduced", "Diff %"], rows))
    for name, title in [("T7_significance", "Sharpe differences (generated)"),
                        ("T11_seeds", "Seed sensitivity (generated)")]:
        d = load(name)
        if d is not None:
            blocks.append(f"### {title}\n\n" + md_table(list(d.columns),
                                                         d.round(4).values.tolist()))
    readme = open(f"{ROOT}/README.md").read()
    readme = re.sub(r"<!-- RESULTS:BEGIN.*?<!-- RESULTS:END -->",
                    "<!-- RESULTS:BEGIN (generated by code/statistics/make_reports.py) -->\n\n" +
                    "\n\n".join(blocks) + "\n\n<!-- RESULTS:END -->",
                    readme, flags=re.S)
    open(f"{ROOT}/README.md", "w").write(readme)

    # ------------------------------------------------------------ paper prose
    R, D, C = [], [], []
    if port is not None:
        d = port.set_index("model")
        R.append("Table~\\ref{tab:portfolio} reports the headline portfolio "
                 "results at baseline costs over the 22 out-of-sample folds.")
        if "kronos" in d.index and "azb_s42" in d.index:
            R.append(f"Kronos attains a Sharpe ratio of {f(d.loc['kronos','sharpe'])} "
                     f"(CAGR {f(d.loc['kronos','cagr'])}, maximum drawdown {f(d.loc['kronos','max_dd'])}, "
                     f"benchmark correlation {f(d.loc['kronos','corr'])}), while AlphaZeroBeta "
                     f"attains {f(d.loc['azb_s42','sharpe'])} "
                     f"(CAGR {f(d.loc['azb_s42','cagr'])}, maximum drawdown {f(d.loc['azb_s42','max_dd'])}, "
                     f"correlation {f(d.loc['azb_s42','corr'])}).")
        if "momentum" in d.index:
            R.append(f"The 12--1 momentum baseline reaches Sharpe {f(d.loc['momentum','sharpe'])} "
                     f"and the walk-forward ridge baseline {f(d.loc['ridge','sharpe'] if 'ridge' in d.index else np.nan)}.")
        if "index_ref" in d.index:
            R.append(f"The passive S\\&P 500 reference has Sharpe {f(d.loc['index_ref','sharpe'])} "
                     f"with a maximum drawdown of {f(d.loc['index_ref','max_dd'])}; the active arms' "
                     "market-neutral construction means this comparison is qualitative only, since the two "
                     "groups are not the same object.")
    if fore is not None:
        k = fore.iloc[0]
        R.append(f"At Level~1, zero-shot Kronos achieves MAE {f(k['mae'],4)} and RMSE {f(k['rmse'],4)} "
                 f"against realised close, directional accuracy {f(k['dir_acc'],4)}, and a mean daily "
                 f"cross-sectional rank IC of {f(k.get('rank_ic_mean'),4)}.")
        if dm:
            R.append(f"The Diebold--Mariano statistic on squared errors against the random-walk "
                     f"benchmark is {f(dm.get('dm'))} with $p={f(dm.get('p_value'))}$, so the "
                     "difference in forecast accuracy is " +
                     ("statistically distinguishable from zero at the 5\\% level."
                      if dm.get("p_value", 1) < 0.05 else
                      "not distinguishable from zero at the 5\\% level."))
    if sig is not None:
        R.append("Table~\\ref{tab:sig} reports the Sharpe differences with 21-day block-bootstrap "
                 "confidence intervals and Newey--West alpha regressions.")
        for _, r in sig.iterrows():
            a, b = LABEL.get(r["model_a"], r["model_a"]), LABEL.get(r["model_b"], r["model_b"])
            sig_txt = ("the interval excludes zero" if (r["ci_lo"] > 0 or r["ci_hi"] < 0)
                       else "the interval contains zero")
            R.append(f"For {a} against {b} the Sharpe difference is {f(r['diff'])} "
                     f"with a 95\\% interval of [{f(r['ci_lo'])}, {f(r['ci_hi'])}]; {sig_txt}.")
    if reg is not None:
        D.append("Regime results are in Table~\\ref{tab:regimes}.")
    if cost is not None:
        D.append("Transaction-cost sensitivity is in Table~\\ref{tab:cost}: a strategy whose Sharpe "
                 "collapses when costs are doubled is not tradable at the assumed turnover.")
    if seeds is not None:
        D.append(f"Across the re-run fold subset and three seeds, AlphaZeroBeta's Sharpe has mean "
                 f"{f(seeds['sharpe'].mean())} and standard deviation {f(seeds['sharpe'].std(ddof=1))}, "
                 f"ranging from {f(seeds['sharpe'].min())} to {f(seeds['sharpe'].max())}. Reporting only "
                 "the best seed would have overstated the result by a measurable margin.")
    if comp is not None:
        D.append("Computational characteristics are in Table~\\ref{tab:compute}; the two systems are "
                 "measured on the same GPU, and Kronos runs zero-shot so it incurs no training cost.")

    C.append("This study does not identify a universally dominant method, and the protocol is "
             "designed so that it cannot pretend to.")
    if "kronos_vs_azb_s42" in v:
        s = v["kronos_vs_azb_s42"]
        C.append(f"The Sharpe difference between the two systems is {f(s['diff'])} "
                 f"(95\\% block-bootstrap interval [{f(s['ci'][0])}, {f(s['ci'][1])}]). " +
                 ("Because the interval excludes zero, the ranking is supported under this "
                  "resampling scheme, in this market, over this period."
                  if s["significant"] else
                  "Because the interval contains zero, the two systems are not distinguishable "
                  "on risk-adjusted return in this market over this period."))
    C.append("The two systems answer different questions. Kronos supplies a forecast, which is "
             "directly testable against a random walk; AlphaZeroBeta supplies a decision, and its "
             "forecasting quality is undefined by construction. Any conclusion that one is simply "
             "'better' would require forcing the agent's value estimates to serve as forecasts, "
             "which is an invention rather than a measurement, and we do not do it.")
    C.append("Where the evidence supports a claim we state it; where an interval contains zero we "
             "say so; where a deviation from the source methodology is unavoidable we list it. The "
             "reproduced AlphaZeroBeta number is a lower bound attributable to a reduced compute "
             "budget, not a refutation of the published figure.")

    def join(x):
        return "\n\n".join(x) if x else "Results pending run completion."

    # patch the paper: replace bracketed placeholders with generated prose
    tex = open(f"{ROOT}/paper/kronos_vs_alphazerobeta.tex").read()
    tex = re.sub(r"\[Results narrative generated from the artefacts\.\]", lambda m: join(R), tex)
    tex = re.sub(r"\[Narrative generated after the runs complete\.\](\s*)\\section\{Threats to Validity\}",
                 lambda m: join(D) + m.group(1) + "\\section{Threats to Validity}", tex)
    tex = re.sub(r"\[Narrative generated after the runs complete\.\](\s*)\\section\*\{Similarity",
                 lambda m: join(C) + m.group(1) + "\\section*{Similarity", tex)
    open(f"{ROOT}/paper/kronos_vs_alphazerobeta.tex", "w").write(tex)
    print("README results block and paper prose regenerated", flush=True)
    print(json.dumps(v, indent=1, default=str)[:1800], flush=True)


if __name__ == "__main__":
    main()
